#---------[ agents ]-----------

[[agents]]
id = "test_agent1"
name = "HoloTester1"
public_address = "HcScIxNpyVQrfbe6v75KgIrnRwftywuk3e6GkbxytTufworeYHtTo6OXX7i4q4a"
key_file = "../../../keyfile.txt"

#---------[ hApps ]-----------

[[dnas]]
file = "../../../dist/threaded_comments.dna.json"
hash = ""
id = "threaded_comments"

[[instances]]
agent = "test_agent1"
dna = "threaded_comments"
id = "test_instance1"

  [instances.storage]
  type = "memory"

#---------[ gateway interfaces ]-----------

[[interfaces]]
admin = true
id = "http interface"

  [interfaces.driver]
  type = "http"
  port = 4000

  [[interfaces.instances]]
  id = "test_instance1"

[[interfaces]]
admin = true
id = "websocket interface"

  [interfaces.driver]
  type = "websocket"
  port = 3000

  [[interfaces.instances]]
  id = "test_instance1"

#---------[ misc ]-----------

[logger]
type = "debug"
